set(DEBUG_COMPILER_FLAGS
    -fno-omit-frame-pointer
    -fstack-protector-strong
    -fcf-protection=full
    -Wno-unknown-pragmas
    -Wall
    -Wextra
    -Wpedantic
    -Wfloat-equal
    -Wconversion
    -Wsign-conversion
    -Wnull-dereference
    -Wdouble-promotion
    -Wimplicit-fallthrough
)