name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: configure
        run: cmake --preset ci
      - name: build-rel
        run: cmake --build --preset ci-rel
      - name: test-rel
        run: ctest --preset ci-rel